Fix MockResponse encoding
rack/rack pull request #1780
Opened 2021-11-24 14:05 UTC by gudel98

During my work connected with rack update, I've noticed that Rack::MockResponse#body returns a string with default ASCII-8BIT encoding. That behavior differs from rack version < 2 where implementation of MockResponse#body was just `super.join`
I decided to implement encoding accept for `body` method for testing encoding of real response.

2021-11-24 15:57 UTC, jeremyevans commented
Thanks for the patch.  Unfortunately, I don't think this is worth doing.  Ruby will automatically change the encoding of 7-bit ASCII strings into other compatible encodings:

```ruby
x = "\xaf".force_encoding('Windows-1251')
b = 'b'.b
x.encoding
# => #<Encoding:Windows-1251>
b.encoding
# => #<Encoding:ASCII-8BIT>
b << x
b.encoding
# => #<Encoding:Windows-1251>
```

Can you come up with a failing test that involves non 7-bit ASCII strings and doesn't require checking the encoding directly?

2021-11-24 16:16 UTC, gudel98 commented
@jeremyevans hm, weird. If u change the code od MockResponse with force_encoding and run the test-case I wrote, u'll see that it fails, cause ruby cannot change the encoding

2021-11-24 16:28 UTC, jeremyevans commented
What I'm saying is your test shouldn't matter in practice.  Can you come up with a failing test that involves non 7-bit ASCII strings and doesn't require checking the encoding directly?

2022-01-25 00:37 UTC, ioquatix commented on lib/rack/mock.rb
> +      encoding = super.join.encoding.to_s
This is too inefficient.

2022-01-25 00:37 UTC, ioquatix commented on lib/rack/mock.rb
> +      buffer = String.new.force_encoding(encoding)
It's better to do `String.new(encoding: ...)`. But not sure about backwards compatibility.

2022-01-25 00:38 UTC, ioquatix requested changes
I don't think we can accept this as is, I agree with @jeremyevans.

2022-01-25 00:49 UTC, jeremyevans commented
@ioquatix If you agree with me, then we should close this.  My point is that there is nothing to fix.  Encoding of 7-bit strings as binary doesn't matter, because they will auto-convert to other encodings if necessary.

2022-01-25 00:49 UTC, closed without merging