Move `Rack::Session` to separate gem.
rack/rack pull request #1805
Opened 2022-02-15 04:54 UTC by ioquatix

This includes https://github.com/rack/rack/pull/1177 + moving code to `rack-session` gem.

2022-02-15 07:23 UTC, ioquatix commented
I've moved all the code, and added references to the repo here so that the tests can pass, confirming the successful migration. Ignore the external tests, as they aren't able to pull in the right source gems.

2022-02-16 19:53 UTC, jeremyevans requested changes
rack/encryptor should be put in the new rack-session gem, and not included with rack. Unless you have plans to use it elsewhere in rack?

Do we plan on keeping the gem dependency on rack-session when rack 3 is released?

2022-02-16 21:56 UTC, ioquatix commented
> rack/encryptor should be put in the new rack-session gem, and not included with rack.

Sorry, this was my mistake, it should be deleted in the subsequent commit, but I missed it.

> Do we plan on keeping the gem dependency on rack-session when rack 3 is released?

I think that's a good question and I don't have a strong opinion, but I guess I could lean slightly towards no. Obviously the compatibility would be a bit more tricky with this direction but it allows us to move forward more cleanly.

2022-02-16 22:02 UTC, tenderlove commented
> rack/encryptor should be put in the new rack-session gem, and not included with rack. Unless you have plans to use it elsewhere in rack?

+1

> Do we plan on keeping the gem dependency on rack-session when rack 3 is released?

I don't think we should.

2022-02-17 00:26 UTC, ioquatix commented
Okay:

- Removed `rack-session` from `rack.gemspec` seems we all agree on that.
- Fixed incorrectly added `lib/rack/encryptor.rb`.

2022-02-18 21:00 UTC, jeremyevans approved these changes
Looks good, but I would remove the entry from the Gemfile (I assume it isn't needed).

2022-02-18 21:04 UTC, ioquatix commented on Gemfile
> +gem "rack-session", git: "https://github.com/rack/rack-session.git"
Yes, now the gem is released, we can move it to the gemspec.

2022-02-22 07:38 UTC, merged

2022-02-22 07:40 UTC, ioquatix commented
@tenderlove I've added `rack-session` as a dependency for Rack (3.0). I suggest we remove this in Rack 3.1. It looks like Rack 3.0 will have a bit of compatibility shims to make the migration a bit easier. It will mean Rack 2.x and 3.x compatible code can work for a while and Rack 3.1 will then drop `rack-session`. Apps that want to pull in `rack-session` can do so and work with Rack 3.0 or 3.1 more easily.

2022-02-22 08:46 UTC, matthewd commented
Dropping a dependency in a non-major version feels more likely to create surprises to me. If rack-session is not compatible with Rack 2.x, can we fix that? (Either within the gem, or by having future versions depend upon Rack >= 3, and releasing a zero-file rack-session 2.0 that depends on Rack < 3?)

2022-02-22 08:54 UTC, ioquatix commented
@matthewd I don't have a strong opinion so feel free to propose a better approach which I hope you can also assist with implementation?