Ignore Range header if served file is 0 bytes
rack/rack pull request #2159
Opened 2024-02-25 06:51 UTC by zarqman

Normally `Rack::Files` truncates a byte range to fit a file's contents--as long as at least some bytes are within range. However, an empty (0 byte) file is a special case since there are no requested bytes that can be within range. 

Previously, 0 byte files requested with a Range header always resulted in a 416 error. This PR changes 0 byte files to ignore the Range header and return the empty file.

Ignoring the Range header is allowed per [RFC 9110 §14.2](https://www.rfc-editor.org/rfc/rfc9110#section-14.2-7).

This improves compatibility with clients that speculatively request files with byte ranges. For example, Nginx's slice / slice_range feature causes all requests to utilize Range. 

Slightly ironically, this also results in a smaller response. (On this basis, it could even be argued to ignore Range for files below 50-100 bytes.)

#### Before
```bash
$ curl -i -H 'Range: bytes=0-1023' http://localhost:3000/favicon.ico
HTTP/1.1 416 Range Not Satisfiable
content-type: image/vnd.microsoft.icon
x-cascade: pass
content-range: bytes */0
Content-Length: 25

Byte range unsatisfiable
```

#### After
```bash
$ curl -i -H 'Range: bytes=0-1023' http://localhost:3000/favicon.ico
HTTP/1.1 200 OK
last-modified: Tue, 15 Jan 2019 21:51:01 GMT
content-type: image/vnd.microsoft.icon
Content-Length: 0
```

2024-02-25 10:46 UTC, ioquatix commented
This seems reasonable to me, @jeremyevans @tenderlove do you have any thoughts or potential security issues?

2024-02-25 17:13 UTC, jeremyevans approved these changes
Seems fine to me.

2024-02-25 22:02 UTC, ioquatix requested changes
This looks good to me. Can you please:

- [ ] Add an entry to the changelog.

Thanks!

2024-02-25 22:02 UTC, ioquatix commented on lib/rack/utils.rb
> +      return nil if size.zero?
I would like to prefix this line with a comment that explains the rationale of ignoring the size if it is zero.

2024-02-26 05:23 UTC, zarqman commented
Changelog and comment both added.

2024-02-26 06:49 UTC, ioquatix approved these changes

2024-02-26 06:51 UTC, merged